backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/ponencias"
public_folder: "assets/img/ponencias"

collections:
  - name: "datos"
    label: "Gestión de Contenidos"
    files:
      - name: "ponencias_pasadas"
        label: "Ponencias Pasadas"
        file: "_data/ponencias_pasadas.yml"
        fields:
          - label: "Lista de Ponencias"
            name: "items"
            widget: "list"
            fields:
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Fecha", name: "fecha", widget: "string"}
              - {label: "Imagen", name: "imagen", widget: "image"}
              - {label: "Descripción", name: "descripcion", widget: "text"}
              - {label: "Enlace", name: "link", widget: "string", required: false}
